### ISSUE TITLE
[BUG] BillingRequestMandateRequest defined twice

### ISSUE THREAD

**Issue by dreinon** [gocardless/gocardless-nodejs#115] opened 2022-03-10 10:38 UTC
Hi!
BillingRequestMandateRequest interface is defined twice in the file, and this leads to exporting only the second.

The implementations are the following:
```ts
// first

/** Type for a billingrequestmandaterequest resource. */
export interface BillingRequestMandateRequest {
    currency: string;
    scheme?: string;
}


// second

/** Type for a billingrequestmandaterequest resource. */
export interface BillingRequestMandateRequest {
    currency: string;
    links: BillingRequestMandateRequestLinks;
    scheme?: string;
    verify: BillingRequestMandateRequestVerify;
}
```

The difference between them is that the second has `links` and `verify` property, which I have looked for in the API Reference in the docs, and regarding to the `links` property, I haven't found any `mandate_request[links]`, and regarding to the `verify` property, it appears in the introduction of the [Billing Requests Section](https://developer.gocardless.com/api-reference/#billing-requests-billing-requests).

The first definition appears in the [create billing request endpoint section](https://developer.gocardless.com/api-reference/#billing-requests-create-a-billingrequest).

Thanks!

**Comment by brettwillis** [comment] 2022-04-29 02:23
Duplicate of #116 which is closed by #120

**Closed** 2022-05-03 10:59 UTC
